const prompts = [
  "Can you hear me?",
  "You're on mute.",
  "Let's circle back.",
  "Can everyone see my screen?",
  "I'll put it in the chat.",
  "Can you repeat that?",
  "Sorry, I was on mute.",
  "Let's take this offline.",
  "Can we table that?",
  "Can you see my screen?",
  "Someone using a virtual avatar",
  "I'll get back to you on that!",
  "Let's schedule a follow-up.",
  "Sorry, I have to jump to another call.",
  "Sorry for the background noise.",
  "Let's take a five-minute break.",
  "Who's speaking?",
  "I think we lost [Name].",
  "Can everyone please mute?",
  "I'll send a calendar invite.",
  "Can you share those slides?",
  "Sorry, I was having technical issues.",
  "Dog barking in the background.",
  "Someone's camera is off.",
  "Echo or feedback noise.",
  "Someone joins late.",
  "Background changes (virtual backgrounds).",
  "Child interruption.",
  "Frozen screen.",
  "Awkward silence.",
  "Loud typing noises.",
  "Someone eating or drinking.",
  "Phone ringing.",
  "Overlapping voices (people talking at the same time).",
  "Awkward goodbyes ('Bye, bye, bye, bye...').",
  "Unexpected visitor in the background.",
  "Someone presenting from their car.",
  "Microphone rustling noises.",
  "Someone using a funny virtual background.",
  "Can you see me?",
  "*Crickets chirping*",
  "Internet connection issues.",
  "Sorry, I was multitasking.",
  "Can you send that to everyone?",
  "Does anyone have any questions?",
  "We'll follow up on that.",
  "Let's move on to the next item.",
  "I think you're breaking up.",
  "Let's give everyone a few more minutes to join.",
  "Please mute if you're not speaking.",
  "I'll ping you later.",
  "I have a hard stop at [time].",
  "Sorry, I was disconnected.",
  "Can we get a quick update?",
  "Can you hear/see me now?",
  "Let me share my screen.",
  "That's a great point.",
  "Let's take a step back",
  "Someone asks for questions and receives none",
  "Let's circle back to that.",
  "Sorry, I cut out there for a second.",
  "Let me take a look.",
  "Let's not get into the weeds."
]

export default prompts;
